import { ThemeConfig, ThemeDefinition } from '../types';

export type { ThemeDefinition };

export const THEMES: Record<string, ThemeConfig> = {
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Design épuré et contemporain, typographie nette et espacement aéré.',
    badge: 'GRATUIT',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    headingFont: "'Plus Jakarta Sans', sans-serif",
    cardRadius: 'rounded-xl',
    cardBg: 'bg-white',
    cardBorder: 'border border-slate-100 shadow-sm',
    pageBg: 'bg-slate-50',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-500',
    accentColor: '#0ea5e9',
    headerStyle: 'compact-card',
    productCardStyle: 'horizontal-dense',
    bgClass: 'bg-slate-50',
    borderColor: 'border-slate-200/80',
    headerBg: 'bg-gradient-to-r from-slate-100 to-slate-200',
    isDark: false,
    titleFont: 'font-sans font-bold',
    bodyFont: 'font-sans',
  },
  maison: {
    id: 'maison',
    name: 'Maison',
    description: 'Ambiance bistrot chaleureux avec typographie avec empattements et teintes douces.',
    badge: 'GRATUIT',
    fontFamily: "'Inter', sans-serif",
    headingFont: "'Playfair Display', serif",
    cardRadius: 'rounded-2xl',
    cardBg: 'bg-[#faf8f5]',
    cardBorder: 'border border-[#ede7df] shadow-sm',
    pageBg: 'bg-[#f4efe6]',
    textPrimary: 'text-[#2c241d]',
    textSecondary: 'text-[#7a6b5e]',
    accentColor: '#c27803',
    headerStyle: 'centered-minimal',
    productCardStyle: 'grid-card',
    bgClass: 'bg-[#f4efe6]',
    borderColor: 'border-[#ede7df]',
    headerBg: 'bg-gradient-to-r from-[#efe5d5] to-[#f4efe6]',
    isDark: false,
    titleFont: 'font-serif font-bold',
    bodyFont: 'font-serif',
  },
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'Intemporel et élégant pour restaurants traditionnels et brasseries.',
    badge: 'GRATUIT',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    headingFont: "'Plus Jakarta Sans', sans-serif",
    cardRadius: 'rounded-lg',
    cardBg: 'bg-white',
    cardBorder: 'border border-gray-200 shadow-none',
    pageBg: 'bg-gray-100',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-600',
    accentColor: '#1e293b',
    headerStyle: 'hero-banner',
    productCardStyle: 'minimal-line',
    bgClass: 'bg-gray-100',
    borderColor: 'border-gray-200',
    headerBg: 'bg-gradient-to-r from-gray-200 to-gray-300',
    isDark: false,
    titleFont: 'font-sans font-semibold',
    bodyFont: 'font-sans',
  },
  'warm-bistro': {
    id: 'warm-bistro',
    name: 'Warm Bistro',
    description: 'Palette terreuse, accents cuivrés et mise en valeur des photos de plats.',
    badge: 'PRO',
    fontFamily: "'Outfit', sans-serif",
    headingFont: "'Outfit', sans-serif",
    cardRadius: 'rounded-2xl',
    cardBg: 'bg-[#fffaf5]',
    cardBorder: 'border border-[#fdecdb] shadow-md',
    pageBg: 'bg-[#fcf5ed]',
    textPrimary: 'text-[#3c2a21]',
    textSecondary: 'text-[#8b6e5c]',
    accentColor: '#d97706',
    headerStyle: 'hero-banner',
    productCardStyle: 'photo-focus',
    bgClass: 'bg-[#fcf5ed]',
    borderColor: 'border-[#fdecdb]',
    headerBg: 'bg-gradient-to-r from-[#fae2c8] to-[#fcf5ed]',
    isDark: false,
    titleFont: 'font-sans font-bold',
    bodyFont: 'font-sans',
  },
  'luxury-gold': {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    description: 'Atmosphère feutrée haut de gamme, fond sombre et touches dorées subtiles.',
    badge: 'PRO',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    headingFont: "'Playfair Display', serif",
    cardRadius: 'rounded-xl',
    cardBg: 'bg-[#18181b]',
    cardBorder: 'border border-amber-900/40 shadow-lg',
    pageBg: 'bg-[#09090b]',
    textPrimary: 'text-amber-50',
    textSecondary: 'text-amber-200/60',
    accentColor: '#eab308',
    headerStyle: 'editorial',
    productCardStyle: 'grid-card',
    bgClass: 'bg-[#09090b]',
    borderColor: 'border-amber-900/40',
    headerBg: 'bg-gradient-to-r from-stone-950 via-zinc-900 to-stone-950',
    isDark: true,
    titleFont: 'font-serif font-bold tracking-wide',
    bodyFont: 'font-sans',
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    description: 'Inspiré de la nature, tons vert sauge et typographie organique fraîche.',
    badge: 'PRO',
    fontFamily: "'Outfit', sans-serif",
    headingFont: "'Outfit', sans-serif",
    cardRadius: 'rounded-2xl',
    cardBg: 'bg-white',
    cardBorder: 'border border-emerald-100 shadow-sm',
    pageBg: 'bg-[#f2f7f4]',
    textPrimary: 'text-[#16382b]',
    textSecondary: 'text-[#487160]',
    accentColor: '#059669',
    headerStyle: 'hero-banner',
    productCardStyle: 'horizontal-dense',
    bgClass: 'bg-[#f2f7f4]',
    borderColor: 'border-emerald-100',
    headerBg: 'bg-gradient-to-r from-emerald-100 to-teal-50',
    isDark: false,
    titleFont: 'font-sans font-bold',
    bodyFont: 'font-sans',
  },
  pulse: {
    id: 'pulse',
    name: 'Pulse',
    description: 'Moderne, vif et contrasté avec accents électriques pour bars & lounges.',
    badge: 'PRO',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    headingFont: "'Plus Jakarta Sans', sans-serif",
    cardRadius: 'rounded-xl',
    cardBg: 'bg-[#111827]',
    cardBorder: 'border border-cyan-900/50 shadow-md',
    pageBg: 'bg-[#030712]',
    textPrimary: 'text-white',
    textSecondary: 'text-cyan-200/70',
    accentColor: '#06b6d4',
    headerStyle: 'hero-banner',
    productCardStyle: 'photo-focus',
    bgClass: 'bg-[#030712]',
    borderColor: 'border-cyan-900/50',
    headerBg: 'bg-gradient-to-r from-slate-950 via-cyan-950 to-slate-950',
    isDark: true,
    titleFont: 'font-sans font-black',
    bodyFont: 'font-sans',
  },
  vibe: {
    id: 'vibe',
    name: 'Vibe',
    description: 'Énergie street food & fast casual dynamique avec cartes percutantes.',
    badge: 'PRO',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    headingFont: "'Plus Jakarta Sans', sans-serif",
    cardRadius: 'rounded-xl',
    cardBg: 'bg-white',
    cardBorder: 'border border-orange-100 shadow-sm',
    pageBg: 'bg-[#fff9f5]',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-500',
    accentColor: '#f97316',
    headerStyle: 'compact-card',
    productCardStyle: 'photo-focus',
    bgClass: 'bg-[#fff9f5]',
    borderColor: 'border-orange-100',
    headerBg: 'bg-gradient-to-r from-orange-100 to-amber-50',
    isDark: false,
    titleFont: 'font-sans font-bold',
    bodyFont: 'font-sans',
  },
};

export function getTheme(themeId?: string | null): ThemeConfig {
  if (!themeId || !THEMES[themeId]) {
    return THEMES.minimal;
  }
  return THEMES[themeId];
}
